/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khoj;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author deeksha
 */
public class SearchEngineUI extends javax.swing.JFrame {

    /**
     * PositionalInvertedIndex class object to start positional
     * Inverted Index.
     */
    SoundExIndexing soundIndexing = new SoundExIndexing();
    PositionalInvertedIndex indexing = new PositionalInvertedIndex();

    /**
     * Creates new form SearchEngineUI
     *
     * @throws java.io.IOException for exception hadling
     */
    public SearchEngineUI() throws IOException {
        initComponents();
        DefaultListModel model = new DefaultListModel();
        jList1.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));

        jLabel1.setFont(new java.awt.Font("Khmer OS System", 0, 12)); // NOI18N
        jLabel1.setText("Enter the query:");

        jButton1.setFont(new java.awt.Font("TakaoPGothic", 1, 15)); // NOI18N
        jButton1.setText("Go");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 3, 15)); // NOI18N
        jLabel2.setText("khoj");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String query = this.jTextField1.getText();
        List<String> results = new ArrayList<>();
        DefaultListModel model = new DefaultListModel();
        if (!query.isEmpty()) {
            QueryProcessor search = null;
            try {
                search = new QueryProcessor(query, soundIndexing,
                    indexing);
            } catch (IOException ex) {
                Logger.getLogger(SearchEngineUI.class.getName())
                    .log(Level.SEVERE, null, ex);
            }
            int queryType = search.queryType;
            switch (queryType) {
                case 1:
                    if (indexing.index.getTermCount() == 0
                        || indexing.bwindex.getTermCount() == 0) {
                        jLabel3.setText("No index found");
                    } else {
                        results = search.multiWordOrQuery();
                        jLabel3.setText("Found "
                            + results.size()
                            + " documents");
                    }
                    break;
                case 2: {
                    try {
                        results = search.specialQuery();
                        int specialQuery = search.specialQueryType;
                        System.out.println(specialQuery);
                        switch (specialQuery) {
                            case 1:
                                jLabel3.setText("Stemming result");
                                break;
                            case 2:
                                jLabel3.setText("Total: "
                                    + results.size());
                                break;
                            case 3:
                                jLabel3.setText("Author's name");
                                break;
                            case 4:
                                if (indexing.fileNames.size() == 0) {
                                    model.addElement("Please check files"
                                        + " on the path.");
                                }
                                model.addElement("Positional Indexing of "
                                    + indexing.fileNames.size()
                                    + " document/s completed.");
                                model.addElement("BiWord Indexing of "
                                    + indexing.fileNames.size()
                                    + " document/s completed.");
                                break;
                            case 5:
                                if (soundIndexing.fileNames.size() == 0) {
                                    model.addElement("Please check files"
                                        + " on the path.");
                                }
                                model.addElement("SoundEx index of "
                                    + soundIndexing.fileNames.size()
                                    + " document/s created");
                                break;
                            default:
                                break;

                        }

                    } catch (IOException ex) {
                        Logger.getLogger(SearchEngineUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                default:
                    break;
            }

            Collections.sort(results);
            for (String result : results) {
                model.addElement(result);
            }
        }

        jList1.setModel(model);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        String clickedValue = jList1.getSelectedValue();
        String fileName;
        if (clickedValue.endsWith(".json")) {
            if (clickedValue.contains("article")) {
                fileName = indexing.returnFilePath() + "/" + clickedValue;
            } else {
                fileName = soundIndexing.returnFilePath() + "/" + clickedValue;
            }
            File file = new File(fileName);
            try {
                java.awt.Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                Logger.getLogger(SearchEngineUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
